# Generated by Django 2.2.4 on 2022-07-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='processResult',
            field=models.IntegerField(null=True),
        ),
    ]
