# Generated by Django 2.2.4 on 2022-07-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foo', '0002_alarm_processresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='alarmDate',
            field=models.DateTimeField(),
        ),
    ]
