# Generated by Django 2.2.4 on 2022-07-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foo', '0004_alarm_processor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='processor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
